import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navigation from './components/Navigation'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const navLinks = [
    {
      name: "Home",
      link: "/"
    },
    {
      name: "teste",
      link: "/teste"
    },
    {
      name: "dashboard",
      link: "/dashboard"
    },
  ]
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation  navLinks={navLinks}/>
        {children}
      </body>
    </html>
  )
}
